FROM postgres

USER postgres
WORKDIR /app

COPY docker/db/dev/*.sql /docker-entrypoint-initdb.d/

COPY --chown=postgres:postgres ./docker/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432