FROM node:20-alpine as build-stage
WORKDIR /app

COPY react/package*.json ./
RUN npm ci

COPY react/ ./
RUN npm run build

FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]